# Generated by Django 4.1.2 on 2022-10-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_pl',
            name='product',
        ),
        migrations.AddField(
            model_name='order_pl',
            name='product',
            field=models.ManyToManyField(to='website.cart'),
        ),
    ]
