# Generated by Django 4.1.2 on 2022-10-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_order_pl_product_order_pl_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order_pl',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
