# Generated by Django 4.1.2 on 2022-10-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_cart_is_active_alter_order_pl_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
    ]
