# Generated by Django 4.1.2 on 2022-10-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_cart_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_pl',
            name='status',
        ),
    ]
