# Generated by Django 4.1.2 on 2022-10-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_cart_is_active_order_pl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='order_pl',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
