# Generated by Django 4.1.2 on 2022-10-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_order_pl_status_wish_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=1000.0),
        ),
    ]
