# Generated by Django 4.1.2 on 2022-11-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
