# Generated by Django 4.1.2 on 2022-11-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
