# Generated by Django 4.1.2 on 2022-11-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_alter_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
    ]
