# Generated by Django 4.1.2 on 2022-11-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_remove_payment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
